/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraries;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteLayout;

public class MyCalendar extends javax.swing.JFrame implements MouseListener{

    Point point;
    
    
    public MyCalendar(Point p) {
        
        initComponents();
        
        point = new Point(p.x-this.getSize().width,p.y);
        
        setLocation(point);
        
        setSize(300,300);
      //  setLocationRelativeTo(null);
        
        backgroundclose.setBackground(Color.red);
        
        
        days.getTableHeader().setFont(new Font("Arial",2,9));
        
        FlowLayout layout = new FlowLayout();
        
        close.addMouseListener(this);
        
        close.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
       setLayout(new AbsoluteLayout());
 
        JComboBox year = new JComboBox();
        
        year.setSize(75,40);
        
        year.setBorder(BorderFactory.createEmptyBorder());
        
        year.setBackground(new java.awt.Color(0.255f,0.255f,0.255f,0.0f));
        
        year.addItem("2019");
        
        year.setVisible(true);
        
            JComboBox month = new JComboBox();
        
        month.setSize(75,40);
        
        month.setBorder(BorderFactory.createEmptyBorder());
        
        month.setBackground(new java.awt.Color(0.255f,0.255f,0.255f,0.0f));
        
        month.addItem("Enero");
        month.addItem("Febrero");
        month.addItem("Marzo");
        month.addItem("Abril");
        month.addItem("Mayo");
        month.addItem("Junio");
        month.addItem("Julio");
        
       // month.setSelectedIndex(3);
        
        month.setVisible(true);
        
        year.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        month.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        header.add(year);
        header.add(month);
        
        header.setVisible(true);
      
        header.setSize(250,30);
        close.setSize(30,30);
        close.setVisible(true);
        
        setVisible(true);
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLayeredPane();
        backgroundclose = new javax.swing.JLayeredPane();
        view = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        days = new javax.swing.JTable();
        close = new javax.swing.JLabel();

        header.setBackground(new java.awt.Color(204, 204, 204));
        header.setOpaque(true);
        header.setLayout(new java.awt.FlowLayout());

        backgroundclose.setBackground(new java.awt.Color(255, 102, 102));
        backgroundclose.setOpaque(true);
        backgroundclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setOpaque(true);
        view.setLayout(new java.awt.BorderLayout());

        days.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        days.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(days);
        if (days.getColumnModel().getColumnCount() > 0) {
            days.getColumnModel().getColumn(4).setMinWidth(20);
        }

        view.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        close.setBackground(new java.awt.Color(255, 102, 102));
        close.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(backgroundclose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
   /*     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalendar().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane backgroundclose;
    private javax.swing.JLabel close;
    private javax.swing.JTable days;
    private javax.swing.JLayeredPane header;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLayeredPane view;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
        if(e.getSource().equals(close)){
            dispose();
        }
        
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
        
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
        if(e.getSource().equals(close)){
            backgroundclose.setBackground(Color.gray);
        }
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
         if(e.getSource().equals(close)){
            backgroundclose.setBackground(Color.red);
        }
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
