package hibernate;
// Generated 14-may-2019 13:07:08 by Hibernate Tools 4.3.1



/**
 * BusinessActivity generated by hbm2java
 */
public class BusinessActivity  implements java.io.Serializable {


     private Integer id;
     private String activity;

    public BusinessActivity() {
    }

    public BusinessActivity(String activity) {
       this.activity = activity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }




}


