package hibernate;
// Generated 30-abr-2019 16:41:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String paternal;
     private String maternal;
     private String street;
     private String city;
     private String state;
     private String zipCode;
     private String ssn;
     private String nationality;
     private Date birthday;
     private String phone;
     private Boolean president;
     private Boolean partner;
     private Boolean manager;

    public Client() {
    }

    public Client(String name, String paternal, String maternal, String street, String city, String state, String zipCode, String ssn, String nationality, Date birthday, String phone, Boolean president, Boolean partner, Boolean manager) {
       this.name = name;
       this.paternal = paternal;
       this.maternal = maternal;
       this.street = street;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.ssn = ssn;
       this.nationality = nationality;
       this.birthday = birthday;
       this.phone = phone;
       this.president = president;
       this.partner = partner;
       this.manager = manager;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPaternal() {
        return this.paternal;
    }
    
    public void setPaternal(String paternal) {
        this.paternal = paternal;
    }
    public String getMaternal() {
        return this.maternal;
    }
    
    public void setMaternal(String maternal) {
        this.maternal = maternal;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Boolean getPresident() {
        return this.president;
    }
    
    public void setPresident(Boolean president) {
        this.president = president;
    }
    public Boolean getPartner() {
        return this.partner;
    }
    
    public void setPartner(Boolean partner) {
        this.partner = partner;
    }
    public Boolean getManager() {
        return this.manager;
    }
    
    public void setManager(Boolean manager) {
        this.manager = manager;
    }




}


