package hibernate;
// Generated 30-abr-2019 16:41:29 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {

     private Integer id;
     private CompanyStatus companyStatus;
     private Executive executive;
     private Taxtation taxtation;
     private BusinessActivity activity;
     private String name;
     private String street;
     private String city;
     private String state;
     private String zipCode;
     private String phone;
     private Date dischargeDate;
     private String fein;
     private Set corporateTaxes = new HashSet(0);
     private Set forms = new HashSet(0);

    public Company() {
    }

    public Company(CompanyStatus companyStatus, Executive executive, Taxtation taxtation, String name, String street, String city, String state, String zipCode, String phone, Date dischargeDate, String fein, Set corporateTaxes, Set forms) {
      
       this.companyStatus = companyStatus;
       this.executive = executive;
       this.taxtation = taxtation;
       this.name = name;
       this.street = street;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.phone = phone;
       this.dischargeDate = dischargeDate;
       this.fein = fein;
       this.corporateTaxes = corporateTaxes;
       this.forms = forms;
    }
   
    public Integer getId() {
        return this.id;
    }

    public BusinessActivity getActivity() {
        return activity;
    }

    public void setActivity(BusinessActivity activity) {
        this.activity = activity;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CompanyStatus getCompanyStatus() {
        return this.companyStatus;
    }
    
    public void setCompanyStatus(CompanyStatus companyStatus) {
        this.companyStatus = companyStatus;
    }
    public Executive getExecutive() {
        return this.executive;
    }
    
    public void setExecutive(Executive executive) {
        this.executive = executive;
    }
    public Taxtation getTaxtation() {
        return this.taxtation;
    }
    
    public void setTaxtation(Taxtation taxtation) {
        this.taxtation = taxtation;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getDischargeDate() {
        return this.dischargeDate;
    }
    
    public void setDischargeDate(Date dischargeDate) {
        this.dischargeDate = dischargeDate;
    }
    public String getFein() {
        return this.fein;
    }
    
    public void setFein(String fein) {
        this.fein = fein;
    }
    public Set getCorporateTaxes() {
        return this.corporateTaxes;
    }
    
    public void setCorporateTaxes(Set corporateTaxes) {
        this.corporateTaxes = corporateTaxes;
    }
    public Set getForms() {
        return this.forms;
    }
    
    public void setForms(Set forms) {
        this.forms = forms;
    }


    


}


