package hibernate;
// Generated 30-abr-2019 16:41:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CorporateStatus generated by hbm2java
 */
public class CorporateStatus  implements java.io.Serializable {


     private Integer id;
     private CorporateTax corporateTax;
     private Date date;
     private String status;

    public CorporateStatus() {
    }

    public CorporateStatus(CorporateTax corporateTax, Date date, String status) {
       this.corporateTax = corporateTax;
       this.date = date;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CorporateTax getCorporateTax() {
        return this.corporateTax;
    }
    
    public void setCorporateTax(CorporateTax corporateTax) {
        this.corporateTax = corporateTax;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


