package hibernate;
// Generated 30-abr-2019 16:41:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Form generated by hbm2java
 */
public class Form  implements java.io.Serializable {


     private Integer id;
     private Company company;
     private Executive executive;
     private Format format;
     private String addressee;
     private String street;
     private String city;
     private String state;
     private String zipCode;
     private Boolean checked;
     private Date date;
     private String commentPrint;
     private String observation;

    public Form() {
    }

    public Form(Company company, Executive executive, Format format, String addressee, String street, String city, String state, String zipCode, Boolean checked, Date date, String commentPrint, String observation) {
       this.company = company;
       this.executive = executive;
       this.format = format;
       this.addressee = addressee;
       this.street = street;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.checked = checked;
       this.date = date;
       this.commentPrint = commentPrint;
       this.observation = observation;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Executive getExecutive() {
        return this.executive;
    }
    
    public void setExecutive(Executive executive) {
        this.executive = executive;
    }
    public Format getFormat() {
        return this.format;
    }
    
    public void setFormat(Format format) {
        this.format = format;
    }
    public String getAddressee() {
        return this.addressee;
    }
    
    public void setAddressee(String addressee) {
        this.addressee = addressee;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public Boolean getChecked() {
        return this.checked;
    }
    
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getCommentPrint() {
        return this.commentPrint;
    }
    
    public void setCommentPrint(String commentPrint) {
        this.commentPrint = commentPrint;
    }
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }




}


