package hibernate;
// Generated 30-abr-2019 16:41:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Provider provider;
     private Integer stock;
     private Date update;

    public Inventory() {
    }

    public Inventory(Product product, Provider provider, Integer stock, Date update) {
       this.product = product;
       this.provider = provider;
       this.stock = stock;
       this.update = update;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Provider getProvider() {
        return this.provider;
    }
    
    public void setProvider(Provider provider) {
        this.provider = provider;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Date getUpdate() {
        return this.update;
    }
    
    public void setUpdate(Date update) {
        this.update = update;
    }




}


