package hibernate;
// Generated 30-abr-2019 16:41:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Taxtation generated by hbm2java
 */
public class Taxtation  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Set companies = new HashSet(0);

    public Taxtation() {
    }

    public Taxtation(String type, Set companies) {
       this.type = type;
       this.companies = companies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set companies) {
        this.companies = companies;
    }




}


